//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroSistema.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estoque
    {
        public int Id { get; set; }
        public int Quantidade { get; set; }
        public decimal Valor { get; set; }
        public int Produto_Cod_Produto { get; set; }
        public int Safra_Cod_Safra { get; set; }
    
        public virtual Produto Produto { get; set; }
        public virtual Safra Safra { get; set; }
    }
}
