//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroSistema.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fazenda
    {
        public Fazenda()
        {
            this.Aplicacaos = new HashSet<Aplicacao>();
            this.CentrodeCustoes = new HashSet<CentrodeCusto>();
            this.Funcionarios = new HashSet<Funcionario>();
            this.Implementos = new HashSet<Implemento>();
            this.ProdDocEntradas = new HashSet<ProdDocEntrada>();
            this.Safras = new HashSet<Safra>();
            this.Talhoes = new HashSet<Talho>();
        }
    
        public int Id { get; set; }
        public string Nome_fazenda { get; set; }
        public string Nome_Proprietario { get; set; }
        public string Endereco { get; set; }
        public string Cidade { get; set; }
        public string UF { get; set; }
        public string Telefone { get; set; }
        public string Encarregado { get; set; }
        public string Area_total { get; set; }
        public string Area_Agricola { get; set; }
        public string CPF_CNPJ { get; set; }
        public string IE { get; set; }
    
        public virtual ICollection<Aplicacao> Aplicacaos { get; set; }
        public virtual ICollection<CentrodeCusto> CentrodeCustoes { get; set; }
        public virtual ICollection<Funcionario> Funcionarios { get; set; }
        public virtual ICollection<Implemento> Implementos { get; set; }
        public virtual ICollection<ProdDocEntrada> ProdDocEntradas { get; set; }
        public virtual ICollection<Safra> Safras { get; set; }
        public virtual ICollection<Talho> Talhoes { get; set; }
    }
}
