//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroSistema.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fornecedor
    {
        public Fornecedor()
        {
            this.DocEntradas = new HashSet<DocEntrada>();
        }
    
        public int Id { get; set; }
        public string NomeFantasia { get; set; }
        public string Cnpj { get; set; }
        public string IE { get; set; }
        public string Endereco { get; set; }
        public string Cidade { get; set; }
        public string Telefone { get; set; }
        public System.DateTime DataCadastro { get; set; }
        public string Obs { get; set; }
        public string Tipo_Fornecedor { get; set; }
        public string RazaoSocial { get; set; }
        public string email { get; set; }
    
        public virtual ICollection<DocEntrada> DocEntradas { get; set; }
    }
}
