//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroSistema.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcionario
    {
        public int Id { get; set; }
        public string Cargo { get; set; }
        public string Nome_Funcionario { get; set; }
        public string Rg { get; set; }
        public string Cpf { get; set; }
        public string Endereco { get; set; }
        public string Cidade { get; set; }
        public string UF { get; set; }
        public System.DateTime Data_Admissao { get; set; }
        public Nullable<System.DateTime> Data_Demissao { get; set; }
        public string Telefone { get; set; }
        public Nullable<decimal> Salario_Atual { get; set; }
        public int Fazenda_Cod_Fazenda { get; set; }
    
        public virtual Fazenda Fazenda { get; set; }
    }
}
