//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroSistema.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        public Produto()
        {
            this.Estoques = new HashSet<Estoque>();
            this.ProdDocEntradas = new HashSet<ProdDocEntrada>();
        }
    
        public int Id { get; set; }
        public string Descricao { get; set; }
        public decimal PrecoCompra { get; set; }
        public decimal PrecoVenda { get; set; }
        public int Tipo_Produto_Cod_TipoProduto { get; set; }
        public int UnidadeMedida_Cod_UnidadeMedida { get; set; }
    
        public virtual ICollection<Estoque> Estoques { get; set; }
        public virtual ICollection<ProdDocEntrada> ProdDocEntradas { get; set; }
        public virtual Tipo_Produto Tipo_Produto { get; set; }
        public virtual UnidadeMedida UnidadeMedida { get; set; }
    }
}
