//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroSistema.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Talho
    {
        public int Id { get; set; }
        public string Talhao { get; set; }
        public decimal Area { get; set; }
        public int Fazenda_Cod_Fazenda { get; set; }
    
        public virtual Fazenda Fazenda { get; set; }
    }
}
