//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroSistema
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AgroDBEntities1 : DbContext
    {
        public AgroDBEntities1()
            : base("name=AgroDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Acesso> Acessoes { get; set; }
        public DbSet<Aplicacao> Aplicacaos { get; set; }
        public DbSet<CentrodeCusto> CentrodeCustoes { get; set; }
        public DbSet<Cliente> Clientes { get; set; }
        public DbSet<DocEntrada> DocEntradas { get; set; }
        public DbSet<Estoque> Estoques { get; set; }
        public DbSet<Fazenda> Fazendas { get; set; }
        public DbSet<Fornecedor> Fornecedors { get; set; }
        public DbSet<Funcionario> Funcionarios { get; set; }
        public DbSet<Implemento> Implementos { get; set; }
        public DbSet<ProdDocEntrada> ProdDocEntradas { get; set; }
        public DbSet<ProdutoAplicacao> ProdutoAplicacaos { get; set; }
        public DbSet<Produto> Produtos { get; set; }
        public DbSet<Safra> Safras { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<Talho> Talhoes { get; set; }
        public DbSet<Tipo_Produto> Tipo_Produto { get; set; }
        public DbSet<UnidadeMedida> UnidadeMedidas { get; set; }
        public DbSet<Usuario> Usuarios { get; set; }
    }
}
