//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroSistema
{
    using System;
    using System.Collections.Generic;
    
    public partial class Implemento
    {
        public Implemento()
        {
            this.Aplicacaos = new HashSet<Aplicacao>();
        }
    
        public int Id { get; set; }
        public string Descricao { get; set; }
        public string Tipo { get; set; }
        public string Ano { get; set; }
        public string Chassi { get; set; }
        public decimal Valor { get; set; }
        public decimal Valor_Hora { get; set; }
        public System.DateTime Data_Compra { get; set; }
        public bool Vendida { get; set; }
        public decimal Venda { get; set; }
        public string Placa { get; set; }
        public Nullable<System.DateTime> Data_Venda { get; set; }
        public int Fazenda_Cod_Fazenda { get; set; }
    
        public virtual ICollection<Aplicacao> Aplicacaos { get; set; }
        public virtual Fazenda Fazenda { get; set; }
    }
}
