//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroSistema
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnidadeMedida
    {
        public UnidadeMedida()
        {
            this.Produtos = new HashSet<Produto>();
        }
    
        public int Id { get; set; }
        public string Unidade { get; set; }
        public string Descricao { get; set; }
    
        public virtual ICollection<Produto> Produtos { get; set; }
    }
}
